---
title: "#TidyTuesday Nobel Prize Winners"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(ggbeeswarm) # install.packages('ggbeeswarm')

## show me the data
nobel_winners <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-14/nobel_winners.csv")
nobel_winner_all_pubs <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-14/nobel_winner_all_pubs.csv")
```

## Modifying [@othomantegazza's code](https://github.com/othomantegazza/code-tidytuesday/blob/master/2-20-nobel-prize.R)

```{r wrangle and plot, echo=FALSE}

## wrangle
nobel <- nobel_winners %>% 
  mutate(age =  prize_year - year(birth_date)) 

## p <- 
nobel %>% 
  ggplot(aes(x = category,
             y = age,
             colour = gender,
             alpha = gender)) +
  ggbeeswarm::geom_beeswarm() +
  coord_flip() +
  scale_color_manual(values = c("#BB1288", "#5867A6")) +
  scale_alpha_manual(values = c(1, .4)) +
  theme_minimal() +
  labs(title = "Way Beyond Gender Imbalance",
       subtitle = "Nobel prize laureates until 2016",
       colour = "Gender",
       alpha = "Gender",
       x = "Category",
       y = "Age",
       caption = "Source: Kaggle | Plot by @othomn")

# I was wondering if with a beeswarm plot you can show also every nobel price as a point. The picture 

# some checks
nobel %>% filter(gender == "Female") %>% select(category, full_name) #%>% View()
nobel %>%
  mutate(age =  prize_year - year(birth_date)) %>% 
  filter(age < 25) %>% select(category, full_name) #%>% View()


# save --------------------------------------------------------------------

png(filename = "plots/2-20-nobel-prize.png",
    res = 300,
    height = 1800,
    width = 2400)
p %>% print()
dev.off()

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


### @geokaramanis's beautiful curve plots
https://twitter.com/geokaramanis/status/1128391346597847040
https://github.com/gkaramanis/tidytuesday/blob/master/week-20/nobel.R
